### ISSUE TITLE
drawGlyph doesn't work

### ISSUE THREAD

**Issue by roberto-arista** [typemytype/drawBotRoboFontExtension#1]
Hi Frederik,
if I try to run the example script in the readme I get this error message:
Traceback (most recent call last):
  File "<untitled>", line 9, in <module>
NameError: name 'drawGlyph' is not defined

Did you change the drawGlyph method?

**Comment by typemytype** [comment]
Not that I know of...

Could another extension fail while executing all startup scripts?

Anything in the output window?

**Comment by roberto-arista** [comment]
I reinstalled 3.82 and now it works.
With 3.82 the output window is clean.

Later I can check again with 3.83.
Does 3.83 work on your systems?

**Comment by typemytype** [comment]
this should solve it

https://github.com/typemytype/drawBotRoboFontExtension/commits/master
