### ISSUE TITLE
DrawBot doing nothing in RF4.2 + MacOS 12.3.1

### ISSUE THREAD

**Issue by BlackFoundry** [typemytype/drawBotRoboFontExtension#14]
The example script does nothing with my software set up (and no traceback)
```from drawBot import *
# reset the drawing stack
newDrawing()
# loop over all glyphs
for glyph in CurrentFont():
	# create a new page
	newPage(1000, 1000)
	# draw each glyph on the page
	drawGlyph(glyph)```

**Comment by BlackFoundry** [comment]
oops, sorry I was running it in the normal Python scripting window :-/

**Comment by typemytype** [comment]
you can `import drawBot` inside RoboFont to generate assets

use `drawBot.newDrawing()` and so on
